command_timeout = 1000

[username]
show_always=true
format='[$user]($style)@'

[hostname]
ssh_only=false

[pijul_channel]
symbol= '\(P\) '
format = 'on [$symbol$channel]($style) '
style="blue"
disabled=false
