import = ["/Users/fxdx/.config/alacritty/themes/themes/everforest_dark.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 15
normal = {family = "Hack Nerd Font"}

[shell]
args = ["--login","-c","tmux"]
program = "/usr/local/bin/fish"

[window]
dynamic_padding = true
# opacity = 0.9
